// This file can be auto-generated by running:
// npx supabase gen types typescript --project-id <project-id> > types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string | null
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email?: string | null
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      resources: {
        Row: {
          id: string
          title: string
          description: string | null
          category: string
          content_type: 'article' | 'video' | 'tool' | 'prompt' | null
          url: string | null
          icon: string | null
          is_featured: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          category: string
          content_type?: 'article' | 'video' | 'tool' | 'prompt' | null
          url?: string | null
          icon?: string | null
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          category?: string
          content_type?: 'article' | 'video' | 'tool' | 'prompt' | null
          url?: string | null
          icon?: string | null
          is_featured?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      courses: {
        Row: {
          id: string
          lane: string
          number: number | null
          title: string
          description: string | null
          overview: string | null
          outcomes: string[] | null
          exercises: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          lane: string
          number?: number | null
          title: string
          description?: string | null
          overview?: string | null
          outcomes?: string[] | null
          exercises?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          lane?: string
          number?: number | null
          title?: string
          description?: string | null
          overview?: string | null
          outcomes?: string[] | null
          exercises?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      bookmarks: {
        Row: {
          id: string
          user_id: string
          resource_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          resource_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          resource_id?: string
          created_at?: string
        }
      }
    }
  }
}
